config/routes.rb
Rails.application.routes.draw do
  devise_for :nurses, controllers: {
    sessions: 'nurses/sessions',
    passwords: 'nurses/passwords',
    registrations: 'nurses/registrations'
  }

  devise_for :patients, controllers: {
  sessions: 'patients/sessions',
  passwords: 'patients/passwords',
  registrations: 'patients/registrations'
  }
  
  get 'questions/index'
  root to: "questions#index"
  resources :questions, only: [:index, :new, :create]
  resources :patient_lists, only: [:index, :new, :create]
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :patient,  optional: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :consultation_content

  validates :consultation_content_id,  numericality: { other_than: 1 }, presence: true
  validates :subject,      length: { maximum: 30 }
  validates :detail,       length: { maximum: 200 }
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_patient!, only: [:index, :new]

  def index
    wd = ["日", "月", "火", "水", "木", "金", "土"]
    time = Time.now
    @date = time.strftime("%Y/%m/%d(#{wd[time.wday]})")
    ampm = time.hour < 12 ? "AM" : "PM"
    @time =time.strftime("#{ampm} %I:%M")
  end
  
  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    unless @question.save
      render :new
    end
  end

  private

  def question_params               
    params.require(:question).permit(:consultation_content_id, :date, :subject, :detail).merge(patient_id: current_patient.id)
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_date_time.html.erb
<div class="date_time">
  <div class = "date"><%= @date %></div>
  <div class = "time"><%= @time %></div>
</div>

app/views/questions/create.html.erb
<div class="create_contents">
  <div class="create_content">
    <div class="comments">
       <div class="comment-1">
          <h1>看護師へ投稿が完了しました。</h1>
       </div>
       <div class="comment-2">
          <h1>　　　後ほど伺いますので</h1>
       </div>
       <div class="comment-3">
          <h1>体温を測ってお待ちください。</h1>
       </div>
       <div class="create-btn">
       　 <%= link_to "TOP", root_path, class: 'btn btn-defalt' %>
       </div>
    </div>
  </div>
</div> 

app/views/questions/index.html.erb
<%= render "date_time" %>
<div class="question_contents">
  <div class="question_content"> 
   <div class="title">
     <h2>今日看護師と話したいことを教えてください</h2>
   </div>
    <div class="question">
       <div class="question_item">
        <%= link_to  new_question_path, class: "question_item" do %>
        <%= button_tag type: "submit", class: "btn btn-default btn-s-md" do %>
            <i class="fas fa-user-nurse fa-3x"></i>
            <i class="fas fa-paper-plane fa-3x"></i>
        <% end %>
        <% end %>
       </div>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="question_new_contents">
 <div class="question_new_content">  
    <div class="question_new_content_title">
     <h2></h2>
    </div> 
    <div class="question_items">
    <%= form_with model: @question, url: questions_path, local: true do |f| %>

      <%= render 'shared/error_messages', model: f.object  %>

      <div class = "item-1">
        <div class="i_line_fix">相談内容</div> 
        <div class="field">
          <%= f.collection_select(:consultation_content_id, ConsultationContent.all, :id, :name, {}, {class:"consultation_content_id"}) %>
        </div> 
      </div> 
      <div class = "item-2">
        <div class="i_line_fix"><p>時期<br>（検査日や発症日を入力）</p></div> 
        <div class="field">
          <%= f.date_field :date, size: "20x30", class: 'form-control'%>
      </div>
      </div>
      <div class = "item-3">
          <div class="i_line_fix">件名</div>
          <div class="field">
            <%= f.text_field :subject, class:"body-region", placeholder:" 例）右足、左手中指、胃カメラについて" %>
          </div>
      </div>
      <div class = "item-4">
          <div class="i_line_fix">詳細</div>
          <div class="field">
            <%= f.text_area :detail, size: "45x10", class:"detail", placeholder:"例）腫れている、検査は何時から？退院時期はいつか" %>
          </div>
      </div>
      <div class="question_content-submit">
        <%= button_tag type: "submit", class: "btn btn-default btn-s-md" do %>
            <i class="fas fa-user-nurse fa-3x"></i>
            <i class="fas fa-paper-plane fa-3x"></i>
        <% end %>
      </div>
    <% end %>
    </div>
 </div>
</div>   