config/routes.rb
Rails.application.routes.draw do
  devise_for :nurses, controllers: {
    sessions: 'nurses/sessions',
    passwords: 'nurses/passwords',
    registrations: 'nurses/registrations'
  }

  devise_for :patients, controllers: {
  sessions: 'patients/sessions',
  passwords: 'patients/passwords',
  registrations: 'patients/registrations'
  }
  
  get 'questions/index'
  root to: "questions#index"
  resources :questions, only: [:index, :new, :create]
  resources :patient_lists, only: [:index, :new, :create]
end

app/models/patient_list.rb
class PatientList < ApplicationRecord
  has_many :patients
  
  validates :list, presence: true
end

app/controllers/patient_lists_controller.rb
class PatientListsController < ApplicationController
  
  def index
    wd = ["日", "月", "火", "水", "木", "金", "土"]
    time = Time.now
    @date = time.strftime("%Y/%m/%d(#{wd[time.wday]})")
    ampm = time.hour < 12 ? "AM" : "PM"
    @time =time.strftime("#{ampm} %I:%M")
    @patient_list = PatientList.new
    @patients = Patient.all.order(:name)
    @questions = Question.where("created_at >= ?", Date.today)
  end

  def new
  end

  def create
    @patient_list = PatientList.new(patient_list_params) 
  end

  private

  def patient_list_params
    params.require(:patient_list).permit(:list).merge(patient_id: params[:patient_id])
  end  

end

app/helpers/patient_lists_helper.rb
module PatientListsHelper
end

app/views/patient_lists/_main_list.html.erb
<div id="list">
  <div class="list_contents">
    <div class="list_table">
    <h1>相談内容一覧</h1>
      <table border="4" width="95%" >
        <thead>
          <tr height="40">
            <th align="center" valign="middle" width="15%">名前</th>
            <th width="9%">部屋番号</th>
            <th width="10%">担当医</th>
            <th width="9%">相談内容</th>
            <th width="9%">時期</th>
            <th width="15%">件名</th>
            <th width="30%">詳細</th>
          </tr>
        </thead>
        <tbody>
          <% @questions.each do |question| %>
           <tr align="center" valign="middle" height="50">           
              <td ><%= question.patient.name %></td>
              <td><%= question.patient.room_number %></td>
              <td><%= question.patient.doctor %></td>
              <td><%= question.consultation_content.name %></td>
              <td><%= question.date %></td>
              <td><%= question.subject %></td>
              <td><%= question.detail %></td>
            </tr>      
           <% end %>        
        </tbody>
      </table>
    </div>
  </div>
</div> 

app/views/patient_lists/_side_bar.html.erb
<div class="side-bar">
  <div class="side-bar-header">
    <div class = "date"><%= @date %></div>
    <div class = "time"><%= @time %></div>
  </div>
  <div class="patient_list_room">
    <div class="title-border"><h2>患者一覧</h2></div>
    <div class="patient_list">
        <%= form_with model: @patient_list, url: patient_lists_path, local: true do |f| %>
          <% @patients.each do |patient| %>
            <div class="patient">
              <ul>
                <li><%= f.check_box :list, {multiple: true}, patient.name, nil %><%= patient.name%></li> 
              </ul>
            </div>
          <% end %>
            <div class="checkup_content-submit">
              <%= f.submit "確認する" , class:"btn" %>
            </div>
        <% end %>
    </div>   
  </div>
</div>

app/views/patient_lists/index.html.erb
<div class = "patient_list_contents">
    <div class = "side">
      <%= render "side_bar" %>
    </div>
      <div class="v_line_fix"></div>
    <div class = "main">
      <%= render "main_list" %>
    </div>
</div> 