config/routes.rb
Rails.application.routes.draw do
  devise_for :nurses, controllers: {
    sessions: 'nurses/sessions',
    passwords: 'nurses/passwords',
    registrations: 'nurses/registrations'
  }

  devise_for :patients, controllers: {
  sessions: 'patients/sessions',
  passwords: 'patients/passwords',
  registrations: 'patients/registrations'
  }
  
  get 'questions/index'
  root to: "questions#index"
  resources :questions, only: [:index, :new, :create]
  resources :patient_lists, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consultation_content.rb
class ConsultationContent < ActiveHash::Base
  self.data = [
    { id: 1, name: '--ここから選択--' },
    { id: 2, name: 'な し' },
    { id: 3, name: '検 査' },
    { id: 4, name: '治 療' },
    { id: 5, name: '症 状' },
    { id: 6, name: 'その他' }
  ]
end

app/models/nurse.rb
class Nurse < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:employee_number]


  VALID_PASSWORD_REGEX = /\A[a-z0-9]+\z/i
  validates :password, format: { with: VALID_PASSWORD_REGEX } 
  
  with_options presence: true do
    validates :name,             length: { maximum: 10 }, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
    validates :employee_number,  length: { is: 8 }, format: { with: /\A[0-9]+\z/ }
  end      

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :questions
  belongs_to :patient_list, optional: true
  belongs_to :nurse,        optional: true

  VALID_PASSWORD_REGEX = /\A[a-z0-9]+\z/i
  validates :password, format: { with: VALID_PASSWORD_REGEX }

  with_options presence: true do
    validates :name,         length: { maximum: 10 }, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
    validates :doctor,       format: { with: /\A[ぁ-んァ-ン一-龥]/ }
    validates :room_number,  format: /\A\d{3}[-]\d{1}\z/
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/models/patient_list.rb
class PatientList < ApplicationRecord
  has_many :patients
  
  validates :list, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :patient,  optional: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :consultation_content

  validates :consultation_content_id,  numericality: { other_than: 1 }, presence: true
  validates :subject,      length: { maximum: 30 }
  validates :detail,       length: { maximum: 200 }
end

app/models/treatment_content.rb
class TreatmentContent < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '治療内容' },
    { id: 3, name: '主治医と話がしたい' }
  ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    case resource
    when Nurse
      patient_lists_path
    when Patient
      root_path
    end
  end
end

app/controllers/nurses/passwords_controller.rb
# frozen_string_literal: true

class Nurses::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/nurses/sessions_controller.rb
# frozen_string_literal: true

class Nurses::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [ :new, :create]

 # GET /resource/sign_in
 # def new
 #   super
 # end

 # POST /resource/sign_in
 # def create
 #   super
 # end

 # DELETE /resource/sign_out
 # def destroy
 #   super
 # end

 # protected

 # If you have extra params to permit, append them to the sanitizer.
 def configure_sign_in_params
   devise_parameter_sanitizer.permit(:sign_in, keys: [ :employee_number])
 end
end

app/controllers/nurses/unlocks_controller.rb
# frozen_string_literal: true

class Nurses::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/patient_lists_controller.rb
class PatientListsController < ApplicationController
  
  def index
    wd = ["日", "月", "火", "水", "木", "金", "土"]
    time = Time.now
    @date = time.strftime("%Y/%m/%d(#{wd[time.wday]})")
    ampm = time.hour < 12 ? "AM" : "PM"
    @time =time.strftime("#{ampm} %I:%M")
    @patient_list = PatientList.new
    @patients = Patient.all.order(:name)
    @questions = Question.where("created_at >= ?", Date.today)
  end

  def new
  end

  def create
    @patient_list = PatientList.new(patient_list_params) 
  end

  private

  def patient_list_params
    params.require(:patient_list).permit(:list).merge(patient_id: params[:patient_id])
  end  

end

app/controllers/patients/sessions_controller.rb
# frozen_string_literal: true

class Patients::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:new, :create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
   devise_parameter_sanitizer.permit(:sign_in, keys: [:room_number])
  end
end

app/controllers/patients/unlocks_controller.rb
# frozen_string_literal: true

class Patients::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_patient!, only: [:index, :new]

  def index
    wd = ["日", "月", "火", "水", "木", "金", "土"]
    time = Time.now
    @date = time.strftime("%Y/%m/%d(#{wd[time.wday]})")
    ampm = time.hour < 12 ? "AM" : "PM"
    @time =time.strftime("#{ampm} %I:%M")
  end
  
  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    unless @question.save
      render :new
    end
  end

  private

  def question_params               
    params.require(:question).permit(:consultation_content_id, :date, :subject, :detail).merge(patient_id: current_patient.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkups_helper.rb
module CheckupsHelper
end

app/helpers/medical_treatments_helper.rb
module MedicalTreatmentsHelper
end

app/helpers/patient_lists_helper.rb
module PatientListsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LWOT２</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <script src="https://kit.fontawesome.com/79643f41c3.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class="wrapper">
      <header class="header">
        <div class="header_bar row">
          <h1 class="grid-1"><a href="/">LWOT2　I leave work on time.</a></h1>
          <% if patient_signed_in? %>   
            <div class="user_nav grid-1">
              <div class="login_patient_name">
                <%= "#{current_patient.name}様" %>
              </div>
                <%= link_to destroy_patient_session_path, method: :delete, class: "post" do %>
                  ログアウト
                <% end %>
                <%= link_to new_nurse_session_path, class: "post" do %>
                  看護師様は<br>こちら
                <% end %>
            </div>
          <% elsif nurse_signed_in? %>
            <div class="user_nav grid-1">
              <div class="login_nurse_name">
               <%= "#{current_nurse.name}様" %>
              </div>
              <%= link_to new_patient_session_path, class: "post" do %>
                患者様は<br>こちら
              <% end %>
              <%= link_to destroy_nurse_session_path, method: :delete, class: "post" do %>
                ログアウト
              <% end %>
            </div>
          <% else %>
            <div class="user_nav grid-1">
              <%= link_to new_patient_session_path, class: "post" do %>
                患者様は<br>こちら
              <% end %>
              <%= link_to new_nurse_session_path, class: "post" do %>
                看護師様は<br>こちら
              <% end %>
            </div>
          <% end %>
        </div>
      </header>
         <%= yield %>
      <footer>
        <p>
          Copyright LWOT2(I leave work on time) 2020.
        </p>
      </footer>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>